name       : libgtk-2
version    : 2.24.31
release    : 22
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gtk+/2.24/gtk+-2.24.31.tar.xz : 68c1922732c7efc08df4656a5366dcc3afdc8791513400dac276009b40954658
homepage   : http://www.gnome.org
license    :
    - LGPL-2.0
summary    :
    - The GTK+ 2 package contains the libraries used for creating graphical user interfaces for applications.
    - ^gtk2-demo : Demonstration of major GTK2 features
component  :
    - desktop.gtk
    - ^gtk2-demo : desktop.gtk
description: |
    The GTK+ 2 package contains the libraries used for creating graphical user interfaces for applications.
patterns   :
    - ^gtk2-demo :
        - /usr/bin/gtk-demo*
        - /usr/share/gtk-2.0/demo
emul32     : yes
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig32(atk)
    - pkgconfig32(atk-bridge-2.0)
    - pkgconfig32(cairo)
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(pango)
    - pkgconfig32(xcomposite)
    - pkgconfig32(xcursor)
    - pkgconfig32(xdamage)
    - pkgconfig32(xfixes)
    - pkgconfig32(xinerama)
    - pkgconfig32(xi)
    - pkgconfig32(xkbcommon)
    - pkgconfig32(xrandr)
    - pkgconfig32(xshmfence)
    - cups-devel
    - cups-32bit-devel
setup      : |
    %apply_patches

    sed -i 's#l \(gtk-.*\).sgml#& -o \1#' docs/faq/Makefile.in
    sed -i 's#l \(gtk-.*\).sgml#& -o \1#' docs/tutorial/Makefile.in

    %reconfigure --prefix=/usr \
                 --disable-static \
                 --enable-xinerama \
                 --with-x \
                 --with-xinput \
                 --enable-explicit-deps \
                 --enable-cups \
                 --enable-man \
                 --enable-gtk-doc \
                 --enable-gtk-doc-html
build      : |
    %make
install    : |
    RUN_QUERY_IMMODULES_TEST=false %make_install

    mv $installdir/usr/bin/gtk-update-icon-cache $installdir/usr/bin/gtk-update-icon-cache-2.0
    mv $installdir/usr/share/man/man1/gtk-update-icon-cache.1 $installdir//usr/share/man/man1/gtk-update-icon-cache-2.0.1
